trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'dev'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'val-oss-$(Build.BuildNumber)'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    overrideParameters: '-storage valdnsfoodxtool'
    deploymentMode: 'Validation'

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Delete Resource Group
  condition: always()
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'dev'
    action: 'DeleteRG'
    resourceGroupName: 'val-oss-$(Build.BuildNumber)'
