trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'Pay-As-You-Go(7cae5f28-46fd-44f0-b620-f45276435127)'
    subscriptionName: '7cae5f28-46fd-44f0-b620-f45276435127'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'open-source'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Validation'

- task: CopyFiles@2
  inputs:
    SourceFolder: '.'
    Contents: '*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'